package com.nse.constants;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface NSEConstant {
	//https://archives.nseindia.com/products/content/sec_bhavdata_full_01062021.csv
	//https://www1.nseindia.com/content/historical/DERIVATIVES/2021/FEB/fo01FEB2021bhav.csv.zip
	final public static String BHAV_DATA_URL = "https://archives.nseindia.com/products/content/sec_bhavdata_full_%s.csv";
	final public static String INDEX_DATA_URL = "https://archives.nseindia.com/content/indices/ind_close_all_%s.csv";
	final public static String OPTIONS_DATA_URL = "https://archives.nseindia.com/content/historical/DERIVATIVES/%s/%s/fo%sbhav.csv.zip";
	final public static String INDEX_DATA_OUTPUT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Index-Data\\ind_close_all_%s.csv";
	final public static String BHAV_DATA_OUTPUT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Bhav-Data\\sec_bhavdata_full_%s.csv";
	final public static String OPTIONS_DATA_OUTPUT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Options-Data\\fo%sbhav.csv.zip";
	final public static String OPTIONS_DATA_OUTPUT_FOLDER_CSV = "E:\\StockResearch\\Data\\NseData\\Options-Data\\extracted\\fo%sbhav.csv";
	final public static String OPTIONS_DATA_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\%s";
	final public static String YEARLY_BO_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\yearly-breakout\\%s";
	final public static String QUARTERLY_BO_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\quarterly-breakout\\%s";
	final public static String MONTHLY_BO_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\monthly-breakout\\%s";
	final public static String WEEKLY_BO_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\weekly-breakout\\%s";
	final public static String DAILY_BO_REPORT_FOLDER = "E:\\StockResearch\\Data\\NseData\\Reports\\daily-breakout\\%s";
	final public static String DAILY_REPORTS_FILE_PATH = "E:\\StockResearch\\Watchlist\\GeneratedReports\\";
	final public static String SUPPORT_RESISTANCES_PATH = "E:\\StockResearch\\Kishore-TradeSetup\\BackTesting\\";
	final public static String NSE_MASTER_DATA = "E:\\myspace\\stocks\\NiftyMasterData.csv";
	// ONLY NIFTY - 50 STOCKS
	final public static String NSE_OPTIONS_STOCK_LIST ="NIFTY,BANKNIFTY,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BHARTIARTL,BPCL,BRITANNIA,CIPLA,DIVISLAB,DRREDDY,EICHERMOT,GRASIM,HCLTECH,HDFC,HDFCBANK,HDFCLIFE,HEROMOTOCO,HINDALCO,HINDUNILVR,ICICIBANK,INDUSINDBK,INFY,JSWSTEEL,KOTAKBANK,LT,M&M,MARUTI,ONGC,RELIANCE,SBILIFE,SBIN,SHREECEM,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,ULTRACEMCO,UPL,WIPRO";
	public static Map<String, String> NSE_OPTIONS_STOCK_MAP = new HashMap<>();
	public static Map<String, String> NSE_ALL_OPTIONS_STOCK_MAP = new HashMap<>();


	//, "","EICHERMOT", "","GRASIM", "","HCLTECH", "","HDFC", "","HDFCBANK", "","HDFCLIFE", "","HEROMOTOCO", "","HINDALCO", "","HINDUNILVR", "","ICICIBANK", "","INDUSINDBK", "","INFY", "","JSWSTEEL", "","KOTAKBANK", "","LT", "","M&M", "","MARUTI", "","ONGC", "","RELIANCE", "","SBILIFE", "","SBIN", "","SHREECEM", "","SUNPHARMA", "","TATACONSUM", "","TATAMOTORS", "","TATASTEEL", "","TCS", "","TECHM", "","TITAN", "","ULTRACEMCO", "","UPL", "","WIPRO"
//	final public static String NSE_OPTIONS_STOCK_LIST ="NIFTY,BANKNIFTY,AARTIIND,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ADANIENT,ADANIPORTS,ALKEM,AMARAJABAT,AMBUJACEM,APLLTD,APOLLOHOSP,APOLLOTYRE,ASHOKLEY,ASIANPAINT,ASTRAL,ATUL,AUBANK,AUROPHARMA,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BALKRISIND,BALRAMCHIN,BANDHANBNK,BANKBARODA,BATAINDIA,BEL,BERGEPAINT,BHARATFORG,BHARTIARTL,BHEL,BIOCON,BOSCHLTD,BPCL,BRITANNIA,BSOFT,CADILAHC,CANBK,CANFINHOME,CHAMBLFERT,CHOLAFIN,CIPLA,COALINDIA,COFORGE,COLPAL,CONCOR,COROMANDEL,CROMPTON,CUB,CUMMINSIND,DABUR,DALBHARAT,DEEPAKNTR,DELTACORP,DIVISLAB,DIXON,DLF,DRREDDY,EICHERMOT,ESCORTS,EXIDEIND,FEDERALBNK,FSL,GAIL,GLENMARK,GMRINFRA,GNFC,GODREJCP,GODREJPROP,GRANULES,GRASIM,GSPL,GUJGASLTD,HAL,HAVELLS,HCLTECH,HDFC,HDFCAMC,HDFCBANK,HDFCLIFE,HEROMOTOCO,HINDALCO,HINDCOPPER,HINDPETRO,HINDUNILVR,HONAUT,IBULHSGFIN,ICICIBANK,ICICIGI,ICICIPRULI,IDEA,IDFC,IDFCFIRSTB,IEX,IGL,INDHOTEL,INDIACEM,INDIAMART,INDIGO,INDUSINDBK,INDUSTOWER,INFY,IOC,IPCALAB,IRCTC,ITC,JINDALSTEL,JKCEMENT,JSWSTEEL,JUBLFOOD,KOTAKBANK,L&TFH,LALPATHLAB,LAURUSLABS,LICHSGFIN,LT,LTI,LTTS,LUPIN,M&M,M&MFIN,MANAPPURAM,MARICO,MARUTI,MCDOWELL-N,MCX,METROPOLIS,MFSL,MGL,MINDTREE,MOTHERSUMI,MPHASIS,MRF,MUTHOOTFIN,NAM-INDIA,NATIONALUM,NAUKRI,NAVINFLUOR,NBCC,NESTLEIND,NMDC,NTPC,OBEROIRLTY,OFSS,ONGC,PAGEIND,PEL,PERSISTENT,PETRONET,PFC,PFIZER,PIDILITIND,PIIND,PNB,POLYCAB,POWERGRID,PVR,RAIN,RAMCOCEM,RBLBANK,RECLTD,RELIANCE,SAIL,SBICARD,SBILIFE,SBIN,SHREECEM,SIEMENS,SRF,SRTRANSFIN,STAR,SUNPHARMA,SUNTV,SYNGENE,TATACHEM,TATACOMM,TATACONSUM,TATAMOTORS,TATAPOWER,TATASTEEL,TCS,TECHM,TITAN,TORNTPHARM,TORNTPOWER,TRENT,TVSMOTOR,UBL,ULTRACEMCO,UPL,VEDL,VOLTAS,WHIRLPOOL,WIPRO,ZEEL";

	//https://www1.nseindia.com/content/indices/ind_close_all_19082021.csv
	//https://archives.nseindia.com/products/content/sec_bhavdata_full_01062021.csv
	//https://archives.nseindia.com/products/content/sec_bhavdata_full_03012018.csv

	//16042021
	final public String DATE_FORMAT = "ddMMyyyy";



	public List<String> quarterlyStartMonths = List.of("JAN", "APR", "JULY", "OCT");

	public static Map<String, String> getNiftyList(){

		if(NSE_OPTIONS_STOCK_MAP.isEmpty()){
			NSE_OPTIONS_STOCK_MAP.put("NIFTY","");
			NSE_OPTIONS_STOCK_MAP.put("BANKNIFTY","");
			NSE_OPTIONS_STOCK_MAP.put("ADANIPORTS", "");
			NSE_OPTIONS_STOCK_MAP.put("ASIANPAINT", "");
			NSE_OPTIONS_STOCK_MAP.put("AXISBANK", "");
			NSE_OPTIONS_STOCK_MAP.put("BAJAJ-AUTO", "");
			NSE_OPTIONS_STOCK_MAP.put("BAJAJFINSV", "");
			NSE_OPTIONS_STOCK_MAP.put("BAJFINANCE", "");
			NSE_OPTIONS_STOCK_MAP.put("BHARTIARTL", "");
			NSE_OPTIONS_STOCK_MAP.put("BPCL", "");
			NSE_OPTIONS_STOCK_MAP.put("BRITANNIA", "");
			NSE_OPTIONS_STOCK_MAP.put("CIPLA", "");
			NSE_OPTIONS_STOCK_MAP.put("DIVISLAB", "");
			NSE_OPTIONS_STOCK_MAP.put("DRREDDY", "");
			NSE_OPTIONS_STOCK_MAP.put("EICHERMOT", "");
			NSE_OPTIONS_STOCK_MAP.put("GRASIM", "");
			NSE_OPTIONS_STOCK_MAP.put("HCLTECH", "");
			NSE_OPTIONS_STOCK_MAP.put("HDFC", "");
			NSE_OPTIONS_STOCK_MAP.put("HDFCBANK", "");
			NSE_OPTIONS_STOCK_MAP.put("HDFCLIFE", "");
			NSE_OPTIONS_STOCK_MAP.put("HEROMOTOCO", "");
			NSE_OPTIONS_STOCK_MAP.put("HINDALCO", "");
			NSE_OPTIONS_STOCK_MAP.put("HINDUNILVR", "");
			NSE_OPTIONS_STOCK_MAP.put("ICICIBANK", "");
			NSE_OPTIONS_STOCK_MAP.put("INDUSINDBK", "");
			NSE_OPTIONS_STOCK_MAP.put("INFY", "");
			NSE_OPTIONS_STOCK_MAP.put("JSWSTEEL", "");
			NSE_OPTIONS_STOCK_MAP.put("KOTAKBANK", "");
			NSE_OPTIONS_STOCK_MAP.put("LT", "");
			NSE_OPTIONS_STOCK_MAP.put("M&M", "");
			NSE_OPTIONS_STOCK_MAP.put("MARUTI", "");
			NSE_OPTIONS_STOCK_MAP.put("ONGC", "");
			NSE_OPTIONS_STOCK_MAP.put("RELIANCE", "");
			NSE_OPTIONS_STOCK_MAP.put("SBILIFE", "");
			NSE_OPTIONS_STOCK_MAP.put("SBIN", "");
			NSE_OPTIONS_STOCK_MAP.put("SHREECEM", "");
			NSE_OPTIONS_STOCK_MAP.put("SUNPHARMA", "");
			NSE_OPTIONS_STOCK_MAP.put("TATACONSUM", "");
			NSE_OPTIONS_STOCK_MAP.put("TATAMOTORS", "");
			NSE_OPTIONS_STOCK_MAP.put("TATASTEEL", "");
			NSE_OPTIONS_STOCK_MAP.put("TCS", "");
			NSE_OPTIONS_STOCK_MAP.put("TECHM", "");
			NSE_OPTIONS_STOCK_MAP.put("TITAN", "");
			NSE_OPTIONS_STOCK_MAP.put("ULTRACEMCO", "");
			NSE_OPTIONS_STOCK_MAP.put("UPL", "");
			NSE_OPTIONS_STOCK_MAP.put("WIPRO","");

		}

		return NSE_OPTIONS_STOCK_MAP;
	}


	public static Map<String, String> getAllOptionsList(){

		if(NSE_ALL_OPTIONS_STOCK_MAP.isEmpty()){
			NSE_ALL_OPTIONS_STOCK_MAP.put("NIFTY","");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BANKNIFTY","");
			NSE_ALL_OPTIONS_STOCK_MAP.put("AMBUJACEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ICICIGI", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GUJGASLTD", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HAVELLS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IDEA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("POWERGRID", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NATIONALUM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HINDALCO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ACC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GMRINFRA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LTF", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CANBK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HINDPETRO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SHRIRAMFIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BALRAMCHIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HDFCLIFE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DIXON", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BALKRISIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("OBEROIRLTY", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDIACEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CANFINHOME", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MFSL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HAL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BOSCHLTD", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ADANIPORTS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDIAMART", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDIGO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NAVINFLUOR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ABB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("AUBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INFY", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IRCTC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ASTRAL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IGL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("UBL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ICICIBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PVRINOX", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("AARTIIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MGL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MARICO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ZYDUSLIFE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("FEDERALBNK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BHARTIARTL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("COLPAL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("UNITDSPR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("AXISBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LUPIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TRENT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TITAN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("COFORGE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PFC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IEX", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NESTLEIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SIEMENS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("EXIDEIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("WIPRO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ALKEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("VOLTAS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CUB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ICICIPRULI", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BPCL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CHAMBLFERT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GODREJPROP", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MPHASIS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LALPATHLAB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("M&M", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MCX", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TECHM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SRF", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LTTS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATAMOTORS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CUMMINSIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SBICARD", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PERSISTENT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BHEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HINDUNILVR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DLF", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PIDILITIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ABCAPITAL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MOTHERSON", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BRITANNIA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("EICHERMOT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DEEPAKNTR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("RELIANCE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ABBOTINDIA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("VEDL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PETRONET", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GRANULES", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("RECLTD", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TCS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATACOMM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BSOFT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CROMPTON", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("M&MFIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("JINDALSTEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDUSINDBK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATASTEEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DABUR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NAUKRI", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HDFCBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ATUL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SUNPHARMA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TVSMOTOR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ONGC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ITC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IOC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDUSTOWER", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SBIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BERGEPAINT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BHARATFORG", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HEROMOTOCO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("INDHOTEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATAPOWER", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GLENMARK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BANKBARODA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LICHSGFIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("RBLBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ASHOKLEY", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BANDHANBNK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HDFCAMC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IDFCFIRSTB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("APOLLOHOSP", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SAIL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ADANIENT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ABFRL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("POLYCAB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("METROPOLIS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DIVISLAB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GAIL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HINDCOPPER", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CIPLA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SYNGENE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MANAPPURAM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IDFC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("IPCALAB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BAJFINANCE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NTPC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DRREDDY", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SHREECEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PNB", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("APOLLOTYRE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PIIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("PAGEIND", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BAJAJFINSV", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MUTHOOTFIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BIOCON", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATACONSUM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("NMDC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GODREJCP", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LTIM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("HCLTECH", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TATACHEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("OFSS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("COALINDIA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ASIANPAINT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("UPL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GRASIM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MRF", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("GNFC", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("JUBLFOOD", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CONCOR", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BATAINDIA", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ZEEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ULTRACEMCO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SUNTV", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("TORNTPHARM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("CHOLAFIN", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("MARUTI", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("BAJAJ-AUTO", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("JSWSTEEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("KOTAKBANK", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("LAURUSLABS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("JKCEMENT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("SBILIFE", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("COROMANDEL", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("ESCORTS", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("DALBHARAT", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("RAMCOCEM", "");
			NSE_ALL_OPTIONS_STOCK_MAP.put("AUROPHARMA", "");
		}
		return NSE_ALL_OPTIONS_STOCK_MAP;
	}
}
